akka {
	loglevel = INFO
	actor {
		default-dispatcher {
			fork-join-executor {
				parallelism-min = 4
				parallelism-factor = 2.0
				parallelism-max = 16
			}
		}
	}
}

akka.http.server {
	request-timeout = infinite
	idle-timeout = infinite
}

akka.io {
	tcp.register-timeout = 55s
}

owlery {
	port = 8080
	host = localhost
	kbs = [
		{
			name = vfb
			location = "http://www.virtualflybrain.org/owl/vfb.owl"
			reasoner = elk
		}
	]
}
